#!/bin/bash
### Copyright 2017 Pixar
###
###    Licensed under the Apache License, Version 2.0 (the "Apache License")
###    with the following modification; you may not use this file except in
###    compliance with the Apache License and the following modification to it:
###    Section 6. Trademarks. is deleted and replaced with:
###
###    6. Trademarks. This License does not grant permission to use the trade
###       names, trademarks, service marks, or product names of the Licensor
###       and its affiliates, except as required to comply with Section 4(c) of
###       the License and to reproduce the content of the NOTICE file.
###
###    You may obtain a copy of the Apache License at
###
###        http://www.apache.org/licenses/LICENSE-2.0
###
###    Unless required by applicable law or agreed to in writing, software
###    distributed under the Apache License with the above modification is
###    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
###    KIND, either express or implied. See the Apache License for the specific
###    language governing permissions and limitations under the Apache License.
###
###

# NOTE: Native bash doesn't have any easy way to parse JSON.
# Instead, you should really use a tool like 'jq' https://stedolan.github.io/jq/.
#
# If you have jq, set its correct path in the JQ variable below.
#
# It's beyond the scope of this example to parse the JSON with regular expressions
# which is a horrible idea anyway.

# Enter your path to jq
JQ=/usr/local/bin/jq

HANDLER_NAME=`basename "$0"`
CHANGELOG='/tmp/smart-computer-group-changes.log'

# read all of stdin into a variable
while read line ; do JSON="$JSON $line" ; done
now=`date +'%Y-%m-%d %H:%M:%S'`
groupname=`echo $JSON | "$JQ" -r '.event.name'`

msg="$now $HANDLER_NAME: Smart Computer Group '$groupname' changed."

echo "$msg" >> "$CHANGELOG"
